// Generated by oriel from the Zig API. Do not edit.

export interface Commands {
  get_items: { args: { category?: string | null; }; result: ({ id?: number; name: string; category: string; location: string; quantity?: number; fill_percentage?: number; unit?: string; desired_quantity?: number; notes?: string; last_scanned_at?: string; updated_at?: string; })[] };
  save_item: { args: { item: { id?: number; name: string; category: string; location: string; quantity?: number; fill_percentage?: number; unit?: string; desired_quantity?: number; notes?: string; last_scanned_at?: string; updated_at?: string; }; }; result: number };
  delete_item: { args: { id: number; }; result: null };
  update_stock: { args: { id: number; quantity: number; fill_percentage: number; }; result: null };
  update_desired: { args: { id: number; desired_quantity: number; }; result: null };
  get_low_stock_analysis: { args: null; result: ({ item: { id?: number; name: string; category: string; location: string; quantity?: number; fill_percentage?: number; unit?: string; desired_quantity?: number; notes?: string; last_scanned_at?: string; updated_at?: string; }; missing_quantity: number; status: string; })[] };
  get_settings: { args: null; result: { provider?: string; baseUrl?: string; apiKey?: string; model?: string; defaultLocation?: string; localBackend?: string; localScanMode?: string; embeddingBackend?: string; matchingLabels?: string; } };
  save_settings: { args: { settings: { provider?: string; baseUrl?: string; apiKey?: string; model?: string; defaultLocation?: string; localBackend?: string; localScanMode?: string; embeddingBackend?: string; matchingLabels?: string; }; }; result: null };
  get_available_models: { args: { baseUrl: string; apiKey?: string | null; }; result: ({ id: string; name: string; vision?: boolean; })[] };
  analyze_image: { args: { location: string; image: string; }; result: { items: ({ name: string; category?: string; quantity?: number; fill_percentage?: number; unit?: string; notes?: string; })[]; summary: string; timing?: { total_ms: number; load_ms?: number; vision_ms?: number; generation_ms?: number; input_tokens?: number; output_tokens?: number; } | null; } };
  system_ai_status: { args: null; result: { state: string; message: string; } };
  system_ai_download: { args: null; result: { state: string; message: string; } };
  embedding_default_labels: { args: null; result: (string)[] };
  embedding_status: { args: null; result: { state?: string; message?: string; supported?: boolean; device?: string; backend?: string; loaded?: boolean; bytes_downloaded?: number; total_bytes?: number; } };
  embedding_download: { args: null; result: { state?: string; message?: string; supported?: boolean; device?: string; backend?: string; loaded?: boolean; bytes_downloaded?: number; total_bytes?: number; } };
  embedding_cancel: { args: null; result: { state?: string; message?: string; supported?: boolean; device?: string; backend?: string; loaded?: boolean; bytes_downloaded?: number; total_bytes?: number; } };
  embedding_prepare: { args: { backend: string; }; result: { state?: string; message?: string; supported?: boolean; device?: string; backend?: string; loaded?: boolean; bytes_downloaded?: number; total_bytes?: number; } };
  embedding_match: { args: { image: string; backend: string; labels: (string)[]; }; result: { matches: ({ label: string; score: number; adjustment?: number; })[]; device: string; backend: string; total_ms: number; load_ms: number; labels_ms: number; image_ms: number; pss_mb: number; dimensions: number; vision_tokens: number; labels_cached: boolean; label_cache?: string; scan_id?: string; correction_count?: number; feedback_warning?: string; labels_count?: number; needs_review?: boolean; background_score?: number; } };
  detect_regions: { args: { image: string; detector: string }; result: { boxes: {x:number;y:number;width:number;height:number;label:string;score:number}[];detector:string;load_ms:number;detect_ms:number;total_ms:number;pss_mb:number } };
  ocr_region: { args: {image:string;rotated:boolean}; result: {text:string;total_ms:number;width:number;height:number;rotations:number;pss_mb:number} };
  embedding_region_match: { args: {image:string;backend:string;labels:string[];use_feedback:boolean}; result: Commands["embedding_match"]["result"] };
  fast_scan: { args: { image: string; }; result: { matches: ({ label: string; score: number; adjustment?: number; })[]; device: string; backend: string; total_ms: number; load_ms: number; labels_ms: number; image_ms: number; pss_mb: number; dimensions: number; vision_tokens: number; labels_cached: boolean; label_cache?: string; scan_id?: string; correction_count?: number; feedback_warning?: string; labels_count?: number; needs_review?: boolean; background_score?: number; } };
  embedding_feedback: { args: { scan_id: string; label: string; accepted: boolean; }; result: { count: number; } };
  embedding_clear_feedback: { args: null; result: { count: number; } };
  embedding_release: { args: null; result: { state?: string; message?: string; supported?: boolean; device?: string; backend?: string; loaded?: boolean; bytes_downloaded?: number; total_bytes?: number; } };
  embedding_delete: { args: null; result: { state?: string; message?: string; supported?: boolean; device?: string; backend?: string; loaded?: boolean; bytes_downloaded?: number; total_bytes?: number; } };
  local_status: { args: null; result: { backend: string; gpu: string | null; models_dir: string; supported: boolean; models: ({ id: string; label: string; mb: number; projector_mb: number; speed: number; quality: number; note: string; present: boolean; partial: boolean; partial_mb: number; })[]; loaded: string | null; loaded_gpu?: boolean; load_ms?: number; downloading: string | null; generating: boolean; } };
  local_download: { args: { id: string; }; result: null };
  local_cancel_download: { args: null; result: null };
  local_delete: { args: { id: string; }; result: null };
  local_unload: { args: null; result: null };
  local_test: { args: { id: string; backend?: string | null; fast?: boolean; }; result: { backend: string; gpu: string | null; ctx: number; vision: boolean; load_ms: number; } };
  apply_scan_results: { args: { location: string; summary: string; items: ({ id?: number; name: string; category: string; location: string; quantity?: number; fill_percentage?: number; unit?: string; desired_quantity?: number; notes?: string; last_scanned_at?: string; updated_at?: string; })[]; }; result: null };
  get_scan_logs: { args: { limit?: number | null; }; result: ({ id?: number; location: string; items_detected_count?: number; summary: string; created_at: string; })[] };
  clear_all_items: { args: null; result: null };
  reset_sample_data: { args: null; result: null };
  app_info: { args: null; result: { zig: string; mode: string; dev: boolean; } };
}

export interface Events {
  inventory_updated: { timestamp: number; };
  scan_completed: { count: number; summary: string; };
  local_model_download: { id: string; state: string; done_mb?: number; total_mb?: number; };
  "permission-changed": { name: PermissionName; status: PermissionStatus };
}

type Args<K extends keyof Commands> = Commands[K]["args"];

export interface WindowOptions {
  label: string;
  url?: string;
  title?: string;
  width?: number;
  height?: number;
  min_width?: number;
  min_height?: number;
  max_width?: number;
  max_height?: number;
  resizable?: boolean;
  decorations?: boolean;
  fullscreen?: boolean;
  maximized?: boolean;
}

export interface WindowHandle {
  readonly label: string;
  close(): Promise<void>;
  show(): Promise<void>;
  hide(): Promise<void>;
  focus(): Promise<void>;
  setTitle(title: string): Promise<void>;
  setSize(width: number, height: number): Promise<void>;
  maximize(maximized?: boolean): Promise<void>;
  fullscreen(fullscreen?: boolean): Promise<void>;
  emit(event: string, payload?: unknown): Promise<void>;
}

export type PermissionName = "microphone" | "camera" | "screen_capture" | "accessibility" | "location" | "notifications" | "system_audio" | "bluetooth" | "local_network";
export type PermissionStatus = "granted" | "denied" | "prompt" | "unknown";

export interface PermissionsApi {
  /** Current status; never prompts. Undeclared permissions are "denied". */
  query(name: PermissionName): Promise<PermissionStatus>;
  /** Ask the user if the OS allows it; resolves with the outcome. */
  request(name: PermissionName): Promise<PermissionStatus>;
  /** Open the OS settings page for the permission; false when there is none. */
  openSettings(name: PermissionName): Promise<boolean>;
}

/** The OS and CPU the app was built for (fixed per build). */
export interface Platform {
  os: "linux" | "macos" | "windows" | "android" | "ios";
  /** Zig's architecture name: "x86_64", "aarch64", ... */
  arch: string;
}

export interface DeepLinkApi {
  current(): Promise<string | null>;
}

export interface WindowApi {
  open(options: WindowOptions): Promise<WindowHandle>;
  current(): WindowHandle;
  get(label: string): Promise<WindowHandle | null>;
  all(): Promise<WindowHandle[]>;
  emitTo(label: string, event: string, payload?: unknown): Promise<void>;
}

declare global {
  interface Window {
    oriel: {
      platform: Platform;
      invoke(cmd: string, args: unknown): Promise<unknown>;
      listen(event: string, callback: (payload: unknown) => void): () => void;
      window: WindowApi;
      deepLink: DeepLinkApi;
      permissions: PermissionsApi;
      openExternal(url: string): Promise<void>;
    };
  }
  const oriel: Window["oriel"];
}

/** Call a Zig command. Rejects with the Zig error name on failure. */
export function invoke<K extends keyof Commands>(
  cmd: K,
  ...args: Args<K> extends null ? [] : [Args<K>]
): Promise<Commands[K]["result"]> {
  return window.oriel.invoke(cmd, args[0] ?? null) as Promise<Commands[K]["result"]>;
}

/** Subscribe to an event emitted from Zig. Returns an unsubscribe function. */
export function listen<K extends keyof Events>(event: K, callback: (payload: Events[K]) => void): () => void {
  return window.oriel.listen(event, callback as (payload: unknown) => void);
}

/** Built-in window management API. */
// Not exported as `window`: that would shadow the global inside this module.
export const orielWindow: WindowApi = (globalThis as any).oriel?.window;
/** Built-in deep link API. */
export const deepLink: DeepLinkApi = (globalThis as any).oriel?.deepLink;
/** Built-in OS permissions API. */
export const permissions: PermissionsApi = (globalThis as any).oriel?.permissions;
/** The OS and CPU the app was built for: `platform.os === "android"`. */
export const platform: Platform = (globalThis as any).oriel?.platform;
/** Global Oriel API object. */
export const oriel: Window["oriel"] = (globalThis as any).oriel;
/** Open a URL in the system's default browser. */
export function openExternal(url: string): Promise<void> {
  return window.oriel.openExternal(url);
}
