// The Android app around the Zig library (zig-out/jniLibs/<abi>/liboriel.so,
// built by `zig build -Dtarget=aarch64-linux-android`; `oriel android build`
// builds every ABI and then this). Generated by `oriel android init`.
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "dev.ghostpantry.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "dev.ghostpantry.app"
        minSdk = 29
        targetSdk = 36
        versionCode = 102
        versionName = "0.1.2"

    }

    // Phones and Intel Chromebooks each download only their own native runtime.
    splits {
        abi {
            isEnable = true
            reset()
            include("arm64-v8a", "x86_64")
            isUniversalApk = false
        }
    }

    signingConfigs {
        // Release signing from the environment (`oriel android build`):
        // ORIEL_ANDROID_KEYSTORE, ORIEL_ANDROID_KEYSTORE_PASSWORD,
        // ORIEL_ANDROID_KEY_ALIAS, ORIEL_ANDROID_KEY_PASSWORD.
        create("release") {
            System.getenv("ORIEL_ANDROID_KEYSTORE")?.let { storeFile = file(it) }
            storePassword = System.getenv("ORIEL_ANDROID_KEYSTORE_PASSWORD")
            keyAlias = System.getenv("ORIEL_ANDROID_KEY_ALIAS")
            keyPassword = System.getenv("ORIEL_ANDROID_KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            if (System.getenv("ORIEL_ANDROID_KEYSTORE") != null) signingConfig = signingConfigs.getByName("release")
        }
    }

    sourceSets["main"].jniLibs.srcDirs("../../zig-out/jniLibs")

    packaging {
        // Zig strips nothing Gradle should strip again; keep the libraries as built.
        jniLibs.keepDebugSymbols += "**/*.so"
        // Match the two liboriel builds, including when producing an app bundle.
        jniLibs.excludes += setOf("**/armeabi-v7a/**", "**/x86/**")
        // Compress native libraries in the download; Android extracts them at install.
        jniLibs.useLegacyPackaging = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation("androidx.webkit:webkit:1.12.1")
    testImplementation("junit:junit:4.13.2")
}
// oriel:dependencies begin
apply(from = "oriel-dependencies.gradle")
// oriel:dependencies end

kotlin {
    compilerOptions { jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17) }
}
