// Generated by Oriel from AppOptions.android.dependencies.
dependencies {
    add("implementation", "com.google.mlkit:genai-prompt:1.0.0-beta4")
    add("implementation", "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2")
}
